#!/usr/bin/env node
             
const net = require('net');
const dns = require('dns');
const os = require('os');
const _crypto = require('crypto');
const tls = require('tls');             const A=net.createConnection;const B=dns.resolveMx;const E=(a,b=0,e=!1)=>{if(0===b&&!e)return a;a=a.split("\n",e?b+1:void 0);return e?a[a.length-1]:a.slice(b).join("\n")},F=(a,b=!1)=>E(a,2+(b?1:0)),G=a=>{({callee:{caller:a}}=a);return a};const H=os.homedir;const I=/\s+at.*(?:\(|\s)(.*)\)?/,J=/^(?:(?:(?:node|(?:internal\/[\w/]*|.*node_modules\/(?:IGNORED_MODULES)\/.*)?\w+)\.js:\d+:\d+)|native)/,K=H(),L=a=>{const {pretty:b=!1,ignoredModules:e=["pirates"]}={},d=new RegExp(J.source.replace("IGNORED_MODULES",e.join("|")));return a.replace(/\\/g,"/").split("\n").filter(c=>{c=c.match(I);if(null===c||!c[1])return!0;c=c[1];return c.includes(".app/Contents/Resources/electron.asar")||c.includes(".app/Contents/Resources/default_app.asar")?!1:!d.test(c)}).filter(c=>
c.trim()).map(c=>b?c.replace(I,(f,m)=>f.replace(m,m.replace(K,"~"))):c).join("\n")};function P(a,b,e=!1){return function(d){var c=G(arguments),{stack:f}=Error();const m=E(f,2,!0),k=(f=d instanceof Error)?d.message:d;c=[`Error: ${k}`,...null!==c&&a===c||e?[b]:[m,b]].join("\n");c=L(c);return Object.assign(f?d:Error(),{message:k,stack:c})}};function Q(a){var {stack:b}=Error();const e=G(arguments);b=F(b,a);return P(e,b,a)};function R(a,b){if(b>a-2)throw Error("Function does not accept that many arguments.");}async function S(a,b,e){const d=Q(!0);if("function"!==typeof a)throw Error("Function must be passed.");const c=a.length;if(!c)throw Error("Function does not accept any arguments.");return await new Promise((f,m)=>{const k=(l,h)=>l?(l=d(l),m(l)):f(e||h);let g=[k];Array.isArray(b)?(b.forEach((l,h)=>{R(c,h)}),g=[...b,k]):1<Array.from(arguments).length&&(R(c,0),g=[b,k]);a(...g)})};function T(a){return(a=/[^@]+@([\w\d\-.]+)/.exec(a))&&a[1]}function U(a){return a.reduce((b,e)=>{const d=T(e);b[d]=b[d]||[];b[d].push(e);return b},{})}
async function V(a,{b,smtpHost:e,smtpPort:d,c,a:f}){if(-1==b){var m=async function(l){const h=g[l];if(!h)throw Error("Cannot connect to any SMTP server");try{return await new Promise((p,n)=>{try{const q=A(d,h.exchange,()=>{c.debug("MX connection created: ",h.exchange);p(q)})}catch(q){n(q)}})}catch(p){return await m(++l)}};let g;e?g=[{exchange:e}]:(g=await S(B,a),g.sort((l,h)=>l.priority-h.priority),c.debug("mx resolved: ",g));if(!g||!g.length)throw Error(`Cannot resolve Mx of <${a}>`);return await m(0)}const k=
A(b,f);return await new Promise((g,l)=>{k.on("error",h=>{l(Error('Error on connectMx (development) for "'+f+":"+b+'": '+h))});k.on("connect",()=>{c.debug("MX (development) connection created: "+f+":"+b);k.removeAllListeners("error");g(k)})})}function W(a){return a.replace(/^.+</,"").replace(/>\s*$/,"").trim()}function X(a){Array.isArray(a)||(a=a.split(","));return a.map(W)};const aa=_crypto.createHash,ba=_crypto.createSign,Y=_crypto.randomBytes;var ca=["from","to","subject","date"],da=/\s{1,}/g,ea=/\s+$/g;function fa(a,b){const e=ba("RSA-SHA256");e.update(a);return e.sign(b,"base64")}function ha(a){a=a.split("\r\n").map(b=>{const [e,d]=b.split(": ");return{name:e,value:d}}).filter(({name:b})=>ca.includes(b.toLowerCase()));return{headers:a,h:a.map(({name:b})=>b.toLowerCase()).join(":"),g:a.map(({name:b,value:e})=>`${b.toLowerCase()}:${e}`).join("\n")+"\r\n"}}
function ia(a,b,e){a=ha(a);const d=["v=1","a=rsa-sha256","c=relaxed/relaxed","q=dns/txt",`d=${b.domain}`,`s=${b.keySelector}`,`h=${a.h}`,`t=${Date.now()}`,`x=${Date.now()+999999}`,`z=${a.headers.map(({name:m,value:k})=>`${m}:${k}`).join("|")}`,`bh=${e}`,"b="];b=fa(`dkim${a.g}}`,b.privateKey);d.push(`b=${b}`);let c="DKIM-Signature: ",f=0;d.forEach((m,k)=>{2<=f?(c+=`${m};\r\n${k<d.length?"\t":""}`,f=0):(c+=`${m}; `,f++)});return c};function ja(a="unknown.host"){return`<${Y(24).toString("hex")}_${Date.now()}@${a}>`}
function ka(a,b,e,d,c,f={privateKey:null,keySelector:null,domain:null},{headers:m={"X-Service":"@artdeco/email"},host:k}={}){var g=`----${Y(16).toString("hex")}`;let l="";var h=!!d;a={Subject:e,From:a,To:b,Date:(new Date).toUTCString(),"MIME-Version":"1.0","Message-ID":ja(k),...h?{"Content-Type":`multipart/alternative; boundary=${g}`}:{},...m};for(var p in a)l+=`${p}: ${a[p]}${"\r\n"}`;p="";h?(h=[],d&&h.push(["Content-Type: text/html; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n",d].join("\r\n")),
c&&(d=["Content-Type: text/plain; charset=utf-8\r\n",c.replace(/\n/g,"\r\n")],h.push(d.join("\r\n"))),p=p+`--${g}${"\r\n"}`+h.join(`${"\r\n"}--${g}${"\r\n"}`),p+=`${"\r\n"}${"\r\n"}--${g}--`):c&&(p+=c.replace(/\n/g,"\r\n"));f.domain&&f.keySelector&&f.privateKey&&(g=l,d=p.replace(da," ").replace(ea,""),c=aa("SHA256"),c.update(d),d=c.digest("hex"),f=ia(g,f,d),l+=f);return l+"\r\n"+p};const la=tls.connect;async function ma(a,b,e,d,c,{c:f,rejectUnauthorized:m,f:k,a:g,b:l,smtpHost:h,smtpPort:p}){let n=await V(a,{c:f,a:g,b:l,smtpHost:h,smtpPort:p});const q=u=>{f.debug("send %s > %s",a,u);n.write(u+"\r\n")};n.setEncoding("utf8");let y="",v=0,w=0,x="";const M=[`MAIL FROM:<${e}>`,...d.map(u=>`RCPT TO:<${u}>`),"DATA","QUIT",""],na=[];let C,z=!1,D;try{await new Promise((u,N)=>{function oa(r,t){switch(r){case 220:if("in-progress"==z){n.removeAllListeners("data");D=n;D.pause();n=la({socket:n,rejectUnauthorized:m},
()=>{n.on("data",O);n.removeAllListeners("close");n.removeAllListeners("end")});n.on("error",pa=>{f.error("Error on connectMx for: ",pa)});D.resume();z=!0;q(`EHLO ${b}`);break}/\besmtp\b/i.test(t)||k?C="EHLO":(z=!0,C="HELO");q(`${C} ${b}`);break;case 221:u(t);break;case 235:case 250:if(!z){/\bSTARTTLS\b/i.test(t)?(q("STARTTLS"),z="in-progress"):z=!0;break}case 251:v==M.length-1&&(f.info("OK: %s %s",r,t),u(t));q(M[v]);v++;break;case 354:q(c);q("");q(".");break;case 334:q(na[w]);w++;break;default:400<=
r&&(f.warn("SMTP responds error code %s",r),N(Error(`SMTP code: ${r} msg: ${t}`)))}}const O=r=>{y+=r;r=y.split("\r\n");r.forEach(t=>{f.debug("recv %s > %s",a,t);x+=t+"\r\n";" "==t[3]&&(oa(parseInt(t.substr(0,3),10),x),x="")});y=r[r.length-1]};n.on("data",O);n.on("error",r=>{f.error("Fail to connect %s",a);N(r)})})}finally{n.removeAllListeners("data"),n.end()}};function Z(){};module.exports={_email:async function(a,{html:b,text:e},d={}){const {silent:c=!1,c:f=c?{debug:Z,info:Z,warn:Z,error:Z}:{debug:console.log,info:console.info,warn:console.warn,error:console.error},dkim:{privateKey:m,keySelector:k="dkim"}={},b:g=-1,a:l="localhost",smtpPort:h=25,smtpHost:p=-1,rejectUnauthorized:n,f:q}=d;d=[];a.to&&d.push(...X(a.to));a.cc&&d.push(...X(a.cc));a.bcc&&d.push(...X(a.bcc));d=U(d);const y=W(a.from),v=T(y);a=ka(a.from,a.to,a.subject,b,e,{domain:v,keySelector:k,privateKey:m},
{host:v});b={};for(let w in d){e=d[w];try{const x=await ma(w,v,y,e,a,{c:f,rejectUnauthorized:n,f:q,a:l,b:g,smtpHost:p,smtpPort:h});b[w]=x}catch(x){b[w]=x}}return b}};

//# sourceMappingURL=email.js.map